<a href="https://colab.research.google.com/github/Eshwar1435/GEN_AI_2072/blob/main/2303A52072_GenAI_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rgression Metrices

In [57]:
ya=[10,20,30,40,50]
yp=[10.2,20.5,30.3,40.8,50.6]

##Without libraries

In [58]:
total=0
sum=0
for i in range(len(ya)):
  sum=sum+(ya[i]-yp[i])**2
mse = sum/len(ya)
print("mean square error : ",mse)

mean square error :  0.27599999999999947


In [59]:
total=0
sum=0
for i in range(len(ya)):
  sum=sum+abs((ya[i]-yp[i]))
mae = sum/len(ya)
print("mean absolute error : ",mae)

mean absolute error :  0.4799999999999997


In [60]:
print("Root mean square error : ",(mse)**0.5)

Root mean square error :  0.5253570214625474


##with libraries

In [61]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error

In [62]:
print("mean square error : ",mean_squared_error(ya,yp))
print("mean absolute error : ",mean_absolute_error(ya,yp))
print("Root mean square error : ",root_mean_squared_error(ya,yp))

mean square error :  0.27599999999999947
mean absolute error :  0.4799999999999997
Root mean square error :  0.5253570214625474


#Classification Metrices

In [63]:
ya1=[0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2]
yp1=[0,0,1,1,2,2,0,1,1,1,2,0,2,1,1,2]

#without libraries


In [64]:
min_label = min(min(ya1), min(yp1))
max_label = max(max(ya1), max(yp1))


num_classes = max_label - min_label + 1

cm = np.array([[0 for _ in range(num_classes)] for _ in range(num_classes)])

for i in range(len(ya1)):
    cm[ya1[i]-min_label][yp1[i]-min_label] += 1

for row in cm:
    print(row)


[2 2 1]
[1 3 2]
[1 2 2]


In [65]:
# cm=np.array(cm)

In [66]:
cm

array([[2, 2, 1],
       [1, 3, 2],
       [1, 2, 2]])

In [67]:
import numpy as np

In [68]:
accuracy = np.sum(np.diagonal(cm)) / np.sum(cm)

precision = np.zeros(num_classes)
recall = np.zeros(num_classes)
f1_score = np.zeros(num_classes)

for i in range(num_classes):
    TP = cm[i, i]  # True Positives
    FP = np.sum(cm[:, i]) - TP  # False Positives
    FN = np.sum(cm[i, :]) - TP  # False Negatives
    TN = np.sum(cm) - (TP + FP + FN)  # True Negatives
    # Precision: TP / (TP + FP)
    precision[i] = TP / (TP + FP) if (TP + FP) > 0 else 0

    # Recall: TP / (TP + FN)
    recall[i] = TP / (TP + FN) if (TP + FN) > 0 else 0

    # F1 Score: 2 * (Precision * Recall) / (Precision + Recall)
    if precision[i] + recall[i] > 0:
        f1_score[i] = 2 * (precision[i] * recall[i]) / (precision[i] + recall[i])
    else:
        f1_score[i] = 0

# Calculate overall precision, recall, and F1-score using numpy
overall_precision = np.mean(precision)
overall_recall = np.mean(recall)
overall_f1_score = np.mean(f1_score)

# Print results
for i in range(num_classes):
    print(f"\nClass {i + min_label}:")
    print(f"  Precision: {precision[i]:.2f}")
    print(f"  Recall: {recall[i]:.2f}")
    print(f"  F1-Score: {f1_score[i]:.2f}")


print("\nMetrics:")
print(f"Overall Accuracy: {accuracy:.2f}")
print(f"Overall Precision: {overall_precision:.2f}")
print(f"Overall Recall: {overall_recall:.2f}")
print(f"Overall F1-Score: {overall_f1_score:.2f}")

print()
print()


Class 0:
  Precision: 0.50
  Recall: 0.40
  F1-Score: 0.44

Class 1:
  Precision: 0.43
  Recall: 0.50
  F1-Score: 0.46

Class 2:
  Precision: 0.40
  Recall: 0.40
  F1-Score: 0.40

Metrics:
Overall Accuracy: 0.44
Overall Precision: 0.44
Overall Recall: 0.43
Overall F1-Score: 0.44




##with libraries

In [69]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score,classification_report,confusion_matrix

In [70]:
print(confusion_matrix(ya1,yp1))

[[2 2 1]
 [1 3 2]
 [1 2 2]]


In [71]:
print(classification_report(ya1,yp1))

              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.43      0.50      0.46         6
           2       0.40      0.40      0.40         5

    accuracy                           0.44        16
   macro avg       0.44      0.43      0.44        16
weighted avg       0.44      0.44      0.44        16



In [72]:
print("\nMetrics:")
print(f"Overall Accuracy: {accuracy_score(ya1,yp1):.2f}")
print(f"Overall Precision: {precision_score(ya1,yp1, average='weighted'):.2f}")
print(f"Overall Recall: {recall_score(ya1,yp1, average='weighted'):.2f}")
print(f"Overall F1-Score: {f1_score(ya1,yp1, average='weighted'):.2f}")


Metrics:
Overall Accuracy: 0.44
Overall Precision: 0.44
Overall Recall: 0.44
Overall F1-Score: 0.44
